spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wechat?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Axon@visionki
  redis:
    database: 13
    host: 127.0.0.1
    port: 6379
    password: win10@visionki     # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5      # 连接池中的最小空闲连接
server:
  port: 8999
# 微信公众号配置
wx:
  mp:
    configs:
      - appId: 微信公众号APPID
        secret: 微信公众号密钥
        token: 微信公众号token
        aesKey: 微信公众号aesKey
# 上传文件 存储到阿里云OSS
aliyun:
  oss:
    endpoint: 阿里云OSS - 地区节点 # http://oss-cn-shenzhen.aliyuncs.com
    accessKeyId: 阿里云OSS - accessKeyId
    accessKeySecret: 阿里云OSS - accessKeySecret
    bucketName: 阿里云OSS - accessKeySecret # 在阿里云创建bucket时填写的名称
    path: 阿里云OSS - 文件夹 #wechat/
    bucketUrl: 阿里云OSS - 外网访问域名 # https://xxx.oss-cn-shenzhen.aliyuncs.com/